# API for Project
GET http://localhost:8000/api/projects/
Content-Type: application/json

###

POST http://localhost:8000/api/projects/
Content-Type: application/json

{
    "name": "GBR-33",
    "latitude": "10.25",
    "longitude": "15"
}

###

PATCH http://localhost:8000/api/projects/4/
Content-Type: application/json

{
    "name": "GBR-32"
}

###

DELETE http://localhost:8000/api/projects/4/
Content-Type: application/json

###

# API for Measurement
GET http://localhost:8000/api/measurements/
Content-Type: application/json

###

POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
    "value": "10.1",
    "project": "4"
}

###

PATCH http://localhost:8000/api/measurements/12/
Content-Type: application/json

{
    "value": "-10.1"
}

###

DELETE http://localhost:8000/api/measurements/11/
Content-Type: application/json
